apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "gcr.io/build-jx-prod/jxlabs-nos/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: jxl-base
      context: .
      kaniko:
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
        cache:
          repo: gcr.io/build-jx-prod/jxlabs-nos-nxmatic/cache
  cluster:
    namespace: jx
    pullSecretName: kaniko-secret
