apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "gcr.io/build-jx-prod/jxlabs-nos-nxmatic/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: jxl-base
      context: .
      kaniko:
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
  cluster:
    namespace: jx
    pullSecretName: kaniko-secret
    resources:
      requests:
        cpu: 4
        memory: 6Gi
      limits:
        cpu: 6
        memory: 8Gi
