apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "gcr.io/build-jx-prod/jxlabs-nos/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: jxl-base
      context: .
      kaniko:
        flags:
          - --single-snapshot
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
  cluster:
    namespace: jx
    pullSecretName: kaniko-secret
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 4
        memory: 4Gi
