apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "localhost:5000/nuxeo/nos/jenkins-x/{{.IMAGE_NAME}}:0.0.0-fix-jenkins-location-latest"
  artifacts:
    - image: jenkins
      context: .
      kaniko:
        dockerfile: Dockerfile
        buildArgs:
          VERSION: 0.0.0-fix-jenkins-location-latest
          SCM_REF: dea3b40 (HEAD -> fix-jenkins-location, origin/fix-jenkins-location)
        buildContext:
          localDir: {}
        cache:
          repo: localhost:5000/nuxeo/nos/jenkins-x/cache
  cluster:
    namespace: nos
